// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0-_MYXfxEtdQo7WP14BbFK2Fvo0oqKI',
    appId: '1:163534625308:web:445b368f0a8feb55e91dd9',
    messagingSenderId: '163534625308',
    projectId: 'stylish-9087e',
    authDomain: 'stylish-9087e.firebaseapp.com',
    storageBucket: 'stylish-9087e.appspot.com',
    measurementId: 'G-M2MHCPN57G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANj5hdT9JQg2Ornan9TPVlijjABvNPmLo',
    appId: '1:163534625308:android:551b6711fe3b3e73e91dd9',
    messagingSenderId: '163534625308',
    projectId: 'stylish-9087e',
    storageBucket: 'stylish-9087e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKN1MgLHHRrlSJLEfH3n3foywEk7ai4WU',
    appId: '1:163534625308:ios:677ab769165c3742e91dd9',
    messagingSenderId: '163534625308',
    projectId: 'stylish-9087e',
    storageBucket: 'stylish-9087e.appspot.com',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKN1MgLHHRrlSJLEfH3n3foywEk7ai4WU',
    appId: '1:163534625308:ios:677ab769165c3742e91dd9',
    messagingSenderId: '163534625308',
    projectId: 'stylish-9087e',
    storageBucket: 'stylish-9087e.appspot.com',
    iosBundleId: 'com.example.stylish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0-_MYXfxEtdQo7WP14BbFK2Fvo0oqKI',
    appId: '1:163534625308:web:0587013957e97261e91dd9',
    messagingSenderId: '163534625308',
    projectId: 'stylish-9087e',
    authDomain: 'stylish-9087e.firebaseapp.com',
    storageBucket: 'stylish-9087e.appspot.com',
    measurementId: 'G-ZSXL2MDVP0',
  );
}
